"""Added partnership table

Revision ID: 0dfb56492de8
Revises: 21a8b6717b78
Create Date: 2020-06-18 14:59:33.736957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfb56492de8'
down_revision = '21a8b6717b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('link', sa.String(length=50), nullable=True),
    sa.Column('picture', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnerships')
    # ### end Alembic commands ###
