"""added region to cycle

Revision ID: 119c1acc45f9
Revises: c2e9706bbb34
Create Date: 2019-01-17 01:17:34.856694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119c1acc45f9'
down_revision = 'c2e9706bbb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycles', sa.Column('region', sa.String(length=60), nullable=True))
    op.create_foreign_key(None, 'meetings', 'mentees', ['mentee_id'], ['id'])
    op.create_foreign_key(None, 'university_applications', 'mentees', ['mentee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'university_applications', type_='foreignkey')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('cycles', 'region')
    op.drop_table('')
    # ### end Alembic commands ###
