"""added exam schedule2

Revision ID: 147c47f3b7a4
Revises: 6967c6d0629e
Create Date: 2019-01-25 18:28:23.575653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147c47f3b7a4'
down_revision = '6967c6d0629e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
