"""empty message

Revision ID: 18cf9bf2e9e3
Revises: a56d6f0c9b53
Create Date: 2019-01-15 08:40:20.083369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cf9bf2e9e3'
down_revision = 'a56d6f0c9b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('mentee_id', sa.Integer(), nullable=True))
    op.add_column('meetings', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'mentors', ['mentor_id'], ['id'])
    op.create_foreign_key(None, 'meetings', 'mentees', ['mentee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'mentor_id')
    op.drop_column('meetings', 'mentee_id')
    # ### end Alembic commands ###
