"""added second major and second minor to mentees

Revision ID: 29976d3fdc6d
Revises: 3e564ad62e4d
Create Date: 2019-03-15 18:41:03.148718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29976d3fdc6d'
down_revision = '3e564ad62e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('second_major_course_id', sa.Integer(), nullable=True))
    op.add_column('mentors', sa.Column('second_minor_course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentors', 'courses', ['second_minor_course_id'], ['id'])
    op.create_foreign_key(None, 'mentors', 'courses', ['second_major_course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_column('mentors', 'second_minor_course_id')
    op.drop_column('mentors', 'second_major_course_id')
    # ### end Alembic commands ###
