"""trying to add table for mentees correctly

Revision ID: 334723f1943b
Revises: f8f59365de33
Create Date: 2019-01-17 00:50:16.754466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334723f1943b'
down_revision = 'f8f59365de33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
