"""test change 1 table

Revision ID: 36776806dab5
Revises: 
Create Date: 2019-01-25 20:15:01.132276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36776806dab5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_exams', sa.Column('test13', sa.DateTime(), nullable=False))
    op.drop_column('scheduled_exams', 'test12')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_exams', sa.Column('test12', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('scheduled_exams', 'test13')
    # ### end Alembic commands ###
