"""added primary contact to mentees

Revision ID: 3e564ad62e4d
Revises: 7cf928b71ac6
Create Date: 2019-03-15 18:34:10.429000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e564ad62e4d'
down_revision = '7cf928b71ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentees', sa.Column('primary_contact_username', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'mentees', 'users', ['primary_contact_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentees', type_='foreignkey')
    op.drop_column('mentees', 'primary_contact_username')
    # ### end Alembic commands ###
