"""added city state to mentor

Revision ID: 4db672723b19
Revises: 762be147f36b
Create Date: 2019-03-06 23:52:21.829621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db672723b19'
down_revision = '762be147f36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('mentors', sa.Column('state', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentors', 'state')
    op.drop_column('mentors', 'city')
    # ### end Alembic commands ###
