"""empty message

Revision ID: 56fc88a4262e
Revises: 18cf9bf2e9e3
Create Date: 2019-01-15 08:43:59.541035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fc88a4262e'
down_revision = '18cf9bf2e9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'mentee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meetings', 'mentor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'mentor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meetings', 'mentee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
