"""added mentee2 as test

Revision ID: 5cf15e1235b8
Revises: 334723f1943b
Create Date: 2019-01-17 00:59:32.548187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf15e1235b8'
down_revision = '334723f1943b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
