"""added role to users

Revision ID: 66cfd74a0dc4
Revises: 83f5af92cf6f
Create Date: 2019-01-31 00:00:36.378556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cfd74a0dc4'
down_revision = '83f5af92cf6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.add_column('pre_users', sa.Column('role_name', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'pre_users', 'role', ['role_name'], ['role_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pre_users', type_='foreignkey')
    op.drop_column('pre_users', 'role_name')
    op.drop_table('role')
    # ### end Alembic commands ###
