"""added exam schedule

Revision ID: 6967c6d0629e
Revises: 70c66e327b4c
Create Date: 2019-01-25 18:27:34.959333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6967c6d0629e'
down_revision = '70c66e327b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('realization_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('mentee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name='exam_schedule_exam_id_fkey'),
    sa.ForeignKeyConstraint(['mentee_id'], ['mentees.id'], name='exam_schedule_mentee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_schedule_pkey')
    )
    # ### end Alembic commands ###
