"""added university to mentor

Revision ID: 762be147f36b
Revises: 0aa1a190564e
Create Date: 2019-02-27 21:51:31.074182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762be147f36b'
down_revision = '0aa1a190564e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentors', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_column('mentors', 'university_id')
    # ### end Alembic commands ###
