"""empty message

Revision ID: 7b31ff2fb401
Revises: f043b091a3a9
Create Date: 2019-01-15 08:51:19.635542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b31ff2fb401'
down_revision = 'f043b091a3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentees', sa.Column('username', sa.String(64), nullable=True))
    op.create_foreign_key(None, 'mentees', 'pre_users', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentees', type_='foreignkey')
    op.drop_column('mentees', 'username')
    # ### end Alembic commands ###
