"""removed table meetings

Revision ID: 7cf928b71ac6
Revises: c1a299c3bed2
Create Date: 2019-03-15 18:11:15.216608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cf928b71ac6'
down_revision = 'c1a299c3bed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mentee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['mentees.id'], name='meetings_mentee_id_fkey'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], name='meetings_mentor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meetings_pkey')
    )
    # ### end Alembic commands ###
