"""added username to uploads

Revision ID: 7f351b66e3c3
Revises: da3dfac41746
Create Date: 2019-01-25 18:16:07.937563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f351b66e3c3'
down_revision = 'da3dfac41746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uploads_username', table_name='uploads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_uploads_username', 'uploads', ['username'], unique=True)
    # ### end Alembic commands ###
