"""empty message

Revision ID: 93c01f6e428c
Revises: e6d8463ab1a3
Create Date: 2019-01-16 00:19:36.018599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c01f6e428c'
down_revision = 'e6d8463ab1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentees', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('mentees', sa.Column('financial_aid', sa.Boolean(), nullable=True))
    op.add_column('mentees', sa.Column('state', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentees', 'state')
    op.drop_column('mentees', 'financial_aid')
    op.drop_column('mentees', 'city')
    # ### end Alembic commands ###
