"""empty message

Revision ID: a56d6f0c9b53
Revises: 5429ce93e8b6
Create Date: 2019-01-15 08:37:14.734372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56d6f0c9b53'
down_revision = '5429ce93e8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('cycle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentors', 'cycles', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_column('mentors', 'cycle_id')
    # ### end Alembic commands ###
