"""updated exams table

Revision ID: bbd9cd11f427
Revises: 6e5d87f38a4c
Create Date: 2019-01-26 11:28:00.408101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd9cd11f427'
down_revision = '6e5d87f38a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exams_user_id_fkey', 'exams', type_='foreignkey')
    op.drop_column('exams', 'user_id')
    op.drop_column('exams', 'score')
    op.add_column('scheduled_exams', sa.Column('score', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_exams', 'score')
    op.add_column('exams', sa.Column('score', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('exams', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exams_user_id_fkey', 'exams', 'pre_users', ['user_id'], ['id'])
    # ### end Alembic commands ###
