"""added title to upload

Revision ID: c1a299c3bed2
Revises: fc04fc0c0dff
Create Date: 2019-03-14 08:44:40.310557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a299c3bed2'
down_revision = 'fc04fc0c0dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('title', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'title')
    # ### end Alembic commands ###
