"""renamed mentee2 as test

Revision ID: c2e9706bbb34
Revises: 5cf15e1235b8
Create Date: 2019-01-17 01:05:50.293044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e9706bbb34'
down_revision = '5cf15e1235b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentees2_username', table_name='mentees2')
    op.drop_table('mentees2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('financial_aid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cycle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], name='mentees2_cycle_id_fkey'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], name='mentees2_mentor_id_fkey'),
    sa.ForeignKeyConstraint(['username'], ['pre_users.username'], name='mentees2_username_fkey'),
    sa.PrimaryKeyConstraint('id', name='mentees2_pkey')
    )
    op.create_index('ix_mentees2_username', 'mentees2', ['username'], unique=True)
    # ### end Alembic commands ###
