"""empty message

Revision ID: c7c0f94546f4
Revises: d5c654376780
Create Date: 2019-01-15 08:12:30.270592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c0f94546f4'
down_revision = 'd5c654376780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentees', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mentees', 'mentors', ['mentor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentees', type_='foreignkey')
    op.drop_column('mentees', 'mentor_id')
    # ### end Alembic commands ###
