"""empty message

Revision ID: e6d8463ab1a3
Revises: 7b31ff2fb401
Create Date: 2019-01-15 08:59:27.645737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d8463ab1a3'
down_revision = '7b31ff2fb401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mentees_username'), 'mentees', ['username'], unique=True)
    op.drop_column('mentees', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentees', sa.Column('datetime', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mentees_username'), table_name='mentees')
    # ### end Alembic commands ###
