"""added mapping mentee universidade

Revision ID: f8f59365de33
Revises: ea3e6c91d241
Create Date: 2019-01-16 23:38:32.392701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f59365de33'
down_revision = 'ea3e6c91d241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
