"""added courses to mentors

Revision ID: fc04fc0c0dff
Revises: 00c49751648d
Create Date: 2019-03-11 10:26:22.338460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc04fc0c0dff'
down_revision = '00c49751648d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('major_course_id', sa.Integer(), nullable=True))
    op.add_column('mentors', sa.Column('minor_course_id', sa.Integer(), nullable=True))
    op.drop_constraint('mentors_major_id_fkey', 'mentors', type_='foreignkey')
    op.create_foreign_key(None, 'mentors', 'courses', ['minor_course_id'], ['id'])
    op.create_foreign_key(None, 'mentors', 'courses', ['major_course_id'], ['id'])
    op.drop_column('mentors', 'major_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentors', sa.Column('major_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.drop_constraint(None, 'mentors', type_='foreignkey')
    op.create_foreign_key('mentors_major_id_fkey', 'mentors', 'courses', ['major_id'], ['id'])
    op.drop_column('mentors', 'minor_course_id')
    op.drop_column('mentors', 'major_course_id')
    # ### end Alembic commands ###
